# Generated by Django 4.0.3 on 2022-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_moviephoto_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviephoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
